import { type NextPage } from "next";
import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import { RiDiscordFill } from "react-icons/ri";

const Home: NextPage = () => {
	return (
		<>
			<Head>
				<title>Create T3 App</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
				<AuthShowcase />
			</main>
		</>
	);
};

export default Home;

const AuthShowcase: React.FC = () => {
	const { data: sessionData } = useSession();

	return (
		<div className="flex flex-col items-center justify-center gap-4">
			{sessionData && (
				<div className="flex items-center justify-center gap-4">
					<span className="text-center text-2xl text-white">
						Logged in as {sessionData.user?.name}
					</span>

					{sessionData.user?.image && (
						// eslint-disable-next-line @next/next/no-img-element
						<img
							src={sessionData.user?.image}
							alt="user image"
							className="h-12 w-12 rounded-full border border-white text-sm"
						/>
					)}
				</div>
			)}
			{sessionData ? (
				<button
					className="rounded-lg bg-white px-10 py-3 font-semibold text-red-400 no-underline transition duration-200 ease-in-out hover:bg-[#5865f2] hover:text-white"
					onClick={() => void signOut()}
				>
					Sign out
				</button>
			) : (
				<button
					className="border-ou flex h-16 w-80 items-center justify-center rounded-lg bg-[#5865f2] px-4 py-3 text-lg font-medium text-white no-underline transition duration-100 ease-in-out hover:bg-[#3c45a5]"
					onClick={() => void signIn("discord")}
				>
					<RiDiscordFill size={24} />
					<span className="flex-grow">Sign in with Discord</span>
				</button>
			)}
		</div>
	);
};
